const Strings = {
    App: {
        TITLE: "Hệ Thống Đăng Ký Sử Dụng Xe",
    },

    Common: {
        ERROR: "Có Lỗi Xảy Ra",
        LOGOUT: "Đăng Xuất",
        NO_DATA: "Không Có Dữ Liệu",
        IMAGE: "Ảnh",
        CAR_TYPE: "Loại Xe",
        SCHEDULE_CODE: "Mã Lịch Trình",
        LICENSE_PLATES: "Biển Số",
        START_LOCATION: "Vị Trí Bắt Đầu",
        END_LOCATION: "Vị Trí Kết Thúc",
        DESTINATION: "Điểm Đến",
        START_DATE: "Ngày Đi",
        END_DATE: "Ngày Về",
        TIME: "Thời Gian",
        STATUS: "Trạng Thái",
        UPDATE: "Cập Nhật",
        CANCEL: "Hủy",
        CONFIRM: "Xác Nhận",
        REVIEW: "Đánh Giá",
        FULL_NAME: "Họ Tên",
        FACULTY: "Thuộc Khoa",
        REASON: "Lý Do Đăng Ký",
        BRAND: "Thương Hiệu",
        NUMBER_OF_TRIPS: "Số Chuyến Đi",
        NUMBER_OF_FAILURES: "Số Lần Hỏng Hóc",
        LICENSE: "Giấy Phép",
        NUMBER_PHONE: "Số Điện Thoại",
        AN_ERROR_OCCURRED: "Đã Xảy Ra Lỗi",
        NO_SCHEDULE: "Không Có Lịch Trình",
        CHOOSE_WARD: "-- Chọn xã phường --",
        CHOOSE_DISTRICT: "-- Chọn quận huyện --",
        CHOOSE_PROVINCE: "-- Chọn tỉnh thành phố --",
        NOTE: "Ghi Chú",
        SUCCESS: "Thành Công",
        INVALID_PHONE_NUMBER: "Số Điện Thoại Không Hợp Lệ",
        UPDATING: "Đang Cập Nhật",
        DETAIL: "Chi Tiết",
        EXIT: "Thoát",
        UPDATE_SCHEDULE: "Cập Nhật Lịch Trình",
        INFO_SCHEDULE: "Thông Tin Lịch Trình",
        FILTER: "Bộ Lọc",
        SEARCH: "Tìm Kiếm",
        REFRESH: "Làm Mới",
        OUT_OF_DATE: "Quá Hạn",
        COMPLETE: "Hoàn Thành",
        CONFIRM_COMPLETED: "Xác Nhận Đã Hoàn Thành",
        SCHEDULE_UPDATE_CONFIRMATION: "Xác Nhận Cập Nhật Lịch Trình",
        DO_YOU_WANT_TO_UPDATE: "Bạn Có Muốn Cập Nhật?",
        SCHEDULE_CANCEL_CONFIRMATION: "Xác Nhận Hủy Lịch Trình",
        DO_YOU_WANT_TO_CANCEL_SCHEDULE: "Bạn Có Muốn Hủy Lịch Trình?",
        DRIVER: "Tài Xế",
        EXPIRED: "Hết Hạn",
        NOT_EXPIRED: "Còn Hạn",
        // CREATE: "Tạo",
        ADD: "Thêm",
    },

    Login: {
        LOGIN_CODE: "Mã Số Đăng Nhập",
        PASSWORD: "Mật Khẩu",
        REMEMBER_ACCOUNT: "Ghi nhớ tôi",
        LOGIN: "Đăng Nhập",
        PLEASE_ENTER_PASSWORD: "Vui Lòng Nhập Mật Khẩu",
        PLEASE_ENTER_CODE: "Vui Lòng Nhập Mã Số",
    },

    MainLayout: {
        TEXT_HEADER: "Công Cụ Quản Lý",
    },

    Home: {
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_COLOR: "Màu Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        VEHICLE_CONDITION: "Tình Trạng: ",
        SCHEDULE: "Lịch Trình: ",
        CAR_INFO: "Thông Tin Xe",
    },

    RentedCar: {
        RENTED_CAR_LIST: "Danh Sách Xe Đã Đăng Ký",
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        SCHEDULE: "Lịch Trình: ",
        SUBSCRIBERS: "Người Đăng Ký: ",
        DRIVER: "Tài Xế: ",
        TIME: "Thời Gian: ",
        REVIEW: "Đánh Giá: ",
        COMMENT: "Bình Luận",
        PHONE: "Số Điện Thoại",
    },

    DialogShowScheduleDriver: {
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        CAR_STATUS: "Trạng Thái: ",
        SCHEDULE: "Lịch Trình: ",
        INFO_SUBSCRIBERS: "Thông Tin Người Đăng Ký: ",
        DRIVER: "Tài Xế: ",
        SCHEDULE_STATUS: "Trạng Thái Lịch Trình: ",
        TIME: "Thời Gian: ",
        FULL_NAME_USER: "Họ Tên:",
        PHONE_USER: "Số Điện Thoại:",
        EMAIL_USER: "Email:",
        NOTE: "Ghi Chú:",
        CAR_RENTAL_REASON: "Mục Đích Sử Dụng Xe: ",
        START_LOCATION: "Điểm Xuất Phát: ",
        END_LOCATION: "Điểm Đến: ",
    },

    DialogShowScheduleAdmin: {
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        CAR_STATUS: "Trạng Thái: ",
        SCHEDULE: "Lịch Trình: ",
        INFO_SUBSCRIBERS: "Thông Tin Người Đăng Ký: ",
        DRIVER: "Tài Xế: ",
        SCHEDULE_STATUS: "Trạng Thái Lịch Trình: ",
        TIME: "Thời Gian: ",
        NAME_CODE: "Họ Tên - Mã Cán Bộ:",
        NAME_CODE_FACULTY: "Họ Tên - Mã Cán Bộ - Thuộc Khoa: ",
        PHONE: "Số Điện Thoại:",
        EMAIL: "Email:",
        NOTE: "Ghi Chú:",
        CAR_RENTAL_REASON: "Mục Đích Sử Dụng Xe: ",
        START_LOCATION: "Điểm Xuất Phát: ",
        END_LOCATION: "Điểm Đến: ",
        INFO_ADMIN: "Thông Tin Admin: ",
        CREATED_AT: "Ngày Đăng Ký: ",
        UPDATED_AT: "Ngày Cập Nhật: ",
        PLEASE_CHOOSE_STATUS: "Vui Lòng Chọn Trạng Thái",
        PLEASE_CHOOSE_DRIVER: "Vui Lòng Chọn Tài Xế",
    },

    CarRegistrationManagement: {
        LIST_OF_VEHICLE_REGISTRATION: "Danh Sách Đăng Ký Xe",
    },

    CarManager: {
        TITLE: "Danh Sách Xe",
        ADD_CAR: "Thêm Xe",
        CAR_CODE: "Mã Xe",
    },

    DriverManagement: {
        ADD_DRIVER: "Thêm Tài Xế",
        DRIVER_CODE: "Mã Tài Xế",
    },

    Statistical: {
        TOTAL_CAR: "Tổng Số Xe",
        TOTAL_DRIVER: "Tống Số Tài Xế",
        TOTAL_TRIPS: "Tống Số Chuyến Đi",
        FORM_IS_PENDING_CONFIRMATION: "Đơn Chờ Xác Nhận",
        LICENSE_EXPIRES: "Giấy Phép Hết Hạn",
    },

    DriverTripManager: {
        TRIP_LIST: "Danh Sách Chuyến Đi",
    },

    TripManager: {
        TRIP_LIST: "Danh Sách Chuyến Đi",
    },

    RentalCar: {
        RENTAL_CAR: "Đăng Ký Xe",
        CAR_REGISTRATRION_INFOMATION: "Thông Tin Đăng Ký Xe",
        ENTER_START_LOCATION: "-- Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Địa Điểm Kết Thúc --",
        ENTER_START_LOCATION: "-- Nhập Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Nhập Địa Điểm Kết Thúc --",
        ENTER_CAR_RENTAL_REASON: "-- Mục Đích Sử Dụng Xe --",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_NOTE: "-- Ghi Chú --",
        ENTER_PHONE_NUMBER: "-- Số Điện Thoại --",
        START_END_DAY: "Ngày Đi - Ngày Về: ",
        CAR_RENTAL_REASON: "Mục Đích Sử Dụng Xe: ",
        START_LOCATION: "Địa Điểm Xuất Phát: ",
        END_LOCATION: "Địa Điểm Kết Thúc: ",
        NOTE: "Ghi Chú: ",
        PHONE_NUMBER: "Số Điện Thoại: ",
        REGISTRATION_CONFIRMATION: "Xác Nhận Đăng Ký",
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_COLOR: "Màu Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        VEHICLE_CONDITION: "Tình Trạng: ",
        SCHEDULE: "Lịch Trình: ",
    },

    UpdateSchedulePending: {
        UPDATE_SCHEDULE: "Cập Nhật Lịch Trình",
        ENTER_START_LOCATION: "-- Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Địa Điểm Kết Thúc --",
        ENTER_START_LOCATION: "-- Nhập Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Nhập Địa Điểm Kết Thúc --",
        ENTER_CAR_RENTAL_REASON: "-- Mục Đích Sử Dụng Xe --",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_NOTE: "-- Ghi Chú --",
        ENTER_PHONE_NUMBER: "-- Số Điện Thoại --",
        START_END_DAY: "Ngày Đi - Ngày Về: ",
        CAR_RENTAL_REASON: "Mục Đích Sử Dụng Xe: ",
        START_LOCATION: "Địa Điểm Xuất Phát: ",
        END_LOCATION: "Địa Điểm Kết Thúc: ",
        NOTE: "Ghi Chú: ",
        PHONE_NUMBER: "Số Điện Thoại: ",
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_COLOR: "Màu Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        VEHICLE_CONDITION: "Tình Trạng: ",
        SCHEDULE: "Lịch Trình: ",
    },

    ModalShowAddress: {
        TITLE_START_LOCATION: "Chọn Địa Chỉ Xuất Phát",
        TITLE_END_LOCATION: "Chọn Địa Chỉ Kết Thúc",
        TITLE_LOCATION: "Chọn Địa Chỉ",
    },

    DialogDriverTripManagerFilter: {
        TITLE: "Bộ Lọc Lịch Trình",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_LOCATION: "-- Địa Điểm --",
        STATUS: "Trạng Thái:",
        CAR_TYPE: "Loại Xe:",
        CHOOSE_CAR_TYPE: "-- Chọn Loại Xe --",
        CHOOSE_STATUS: "-- Chọn Trạng Thái --",
        CHOOSE_DRIVER: "-- Chọn Tài Xế --",
        SCHEDULE_CODE: "Mã Lịch Trình:",
        ENTER_SCHEDULE_CODE: "-- Nhập Mã Lịch Trình --",
        TIME: "Thời Gian: ",
        ADDRESS: "Địa Chỉ: ",
    },

    DialogRentedCarFilter: {
        TITLE: "Bộ Lọc Lịch Trình",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_LOCATION: "-- Địa Điểm --",
        STATUS: "Trạng Thái:",
        CAR_TYPE: "Loại Xe:",
        CHOOSE_CAR_TYPE: "-- Chọn Loại Xe --",
        CHOOSE_STATUS: "-- Chọn Trạng Thái --",
        SCHEDULE_CODE: "Mã Lịch Trình:",
        ENTER_SCHEDULE_CODE: "-- Nhập Mã Lịch Trình --",
        TIME: "Thời Gian: ",
        ADDRESS: "Địa Chỉ: ",
    },

    DialogCarRegistrationManagementFilter: {
        TITLE: "Bộ Lọc Lịch Trình",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_LOCATION: "-- Địa Điểm --",
        STATUS: "Trạng Thái:",
        FACULTY: "Khoa:",
        CAR_TYPE: "Loại Xe:",
        CHOOSE_CAR_TYPE: "-- Chọn Loại Xe --",
        CHOOSE_STATUS: "-- Chọn Trạng Thái --",
        CHOOSE_FACULTY: "-- Chọn Khoa --",
        SCHEDULE_CODE: "Mã Lịch Trình:",
        SUBSCRIBERS: "Người Đăng Ký:",
        DRIVER: "Tài Xế:",
        LICENSE_PLATES: "Biển Số Xe:",
        ENTER_SCHEDULE_CODE: "-- Nhập Mã Lịch Trình --",
        ENTER_NAME_CODE_USER: "-- Nhập Tên Hoặc Mã CB Người Đăng Ký --",
        ENTER_NAME_CODE_DRIVER: "-- Nhập Tên Hoặc Mã CB Tài Xế --",
        ENTER_LICENSE_PLATES: "-- Nhập Biển Số Xe --",
        TIME: "Thời Gian: ",
        ADDRESS: "Địa Chỉ: ",
    },
    DialogCarManagerFilter: {
        TITLE: "Bộ Lọc Xe",
        LICENSE_PLATES: "Biển Số Xe:",
        ENTER_LICENSE_PLATES: "-- Nhập Biển Số Xe --",
        CAR_CODE: "Mã Số Xe: ",
        ENTER_CAR_CODE: "-- Nhập Mã Số Xe --",
        BRAND: "Thương Hiệu: ",
        CHOOSE_BRAND: "-- Chọn Thương Hiệu --",
        CAR_STATUS: "Trạng Thái Xe:",
        CAR_TYPE: "Loại Xe:",
        CHOOSE_CAR_TYPE: "-- Chọn Loại Xe --",
        CHOOSE_CAR_STATUS: "-- Chọn Trạng Thái Xe --",
    },
    DialogCreateCar: {
        TITLE: "Thêm Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        ENTER_LICENSE_PLATES: "-- Nhập Biển Số Xe --",
        CAR_TYPE: "Loại Xe: ",
        CHOOSE_CAR_TYPE: "-- Chọn Loại Xe --",
        CAR_BRAND: "Thương Hiệu: ",
        CHOOSE_CAR_BRAND: "-- Chọn Thương Hiệu --",
        CAR_COLOR: "Màu Xe: ",
        CHOOSE_CAR_COLOR: "-- Chọn Màu Xe --",
        CAR_REGISTRATION_CERTIFICATE: "Giấy Đăng Ký Xe: ",
        CHOOSE_TIME_CAR_REGISTRATION_CERTIFICATE:
            "-- Chọn Thời Gian Giấy Đăng Ký Xe --",
        CHOOSE_TIME_PERIODIC_INSPECTION_CERTIFICATE:
            "-- Chọn Thời Gian Giấy Đăng Kiểm Xe --",
        CHOOSE_TIME_CAR_INSURANCE: "-- Chọn Thời Gian Giấy Bảo Hiểm Xe --",
        PERIODIC_INSPECTION_CERTIFICATE: "Giấy Đăng Kiểm Xe: ",
        CAR_INSURANCE: "Giấy Bảo Hiểm Xe: ",
        CHOOSE_TIME: "-- Chọn Thời Gian -- ",
        CHOOSE_IMAGE_PLEASE: "Vui Lòng Chọn Hình Ảnh",
        ENTER_LICENSE_PLATES_PLEASE: "Vui Lòng Nhập Biển Số Xe",
        CHOOSE_CAR_TYPE_PLEASE: "Vui Lòng Chọn Loại Xe",
        CHOOSE_CAR_BRAND_PLEASE: "Vui Lòng Chọn Thương Hiệu",
        CHOOSE_CAR_COLOR_PLEASE: "Vui Lòng Chọn Màu Xe",
        CHOOSE_TIME_PLEASE: "Vui Lòng Chọn Thời Gian",
    },
};

export default Strings;
