const Strings = {
    App: {
        TITLE: "Hệ Thống Đăng Ký Sử Dụng Xe",
    },

    Common: {
        ERROR: "Có Lỗi Xảy Ra",
        LOGOUT: "Đăng Xuất",
        NO_DATA: "Không Có Dữ Liệu",
        IMAGE: "Ảnh",
        CAR_TYPE: "Loại Xe",
        SCHEDULE_CODE: "Mã Lịch Trình",
        LICENSE_PLATES: "Biển Số",
        START_LOCATION: "Vị Trí Bắt Đầu",
        END_LOCATION: "Vị Trí Kết Thúc",
        DESTINATION: "Điểm Đến",
        START_DAY: "Ngày Đi",
        END_DAY: "Ngày Về",
        TIME: "Thời Gian",
        STATUS: "Trạng Thái",
        UPDATE: "Cập Nhật",
        CANCEL: "Hủy",
        CONFIRM: "Xác Nhận",
        REVIEW: "Đánh Giá",
        FULL_NAME: "Họ Tên",
        DEPARTMENT: "Thuộc Khoa",
        REASON: "Lý Do Đăng Ký",
        BRAND: "Thương Hiệu",
        NUMBER_OF_TRIPS: "Số Chuyến Đi",
        NUMBER_OF_FAILURES: "Số Lần Hỏng Hóc",
        LICENSE: "Giấy Phép",
        NUMBER_PHONE: "Số Điện Thoại",
        AN_ERROR_OCCURRED: "Đã Xảy Ra Lỗi",
        NO_SCHEDULE: "Không Có Lịch Trình",
        CHOOSE_WARD: "-- Chọn xã phường --",
        CHOOSE_DISTRICT: "-- Chọn quận huyện --",
        CHOOSE_PROVINCE: "-- Chọn tỉnh thành phố --",
        NOTE: "Ghi Chú",
        SUCCESS: "Thành Công",
        INVALID_PHONE_NUMBER: "Số Điện Thoại Không Hợp Lệ",
        UPDATING: "Đang Cập Nhật",
        DETAIL: "Chi Tiết",
        EXIT: "Thoát",
        UPDATE_SCHEDULE: "Cập Nhật Lịch Trình",
        INFO_SCHEDULE: "Thông Tin Lịch Trình",
        FILTER: "Bộ Lọc",
        SEARCH: "Tìm Kiếm",
        REFRESH: "Làm Mới",
    },

    Login: {
        LOGIN_CODE: "Mã Số Đăng Nhập",
        PASSWORD: "Mật Khẩu",
        REMEMBER_ACCOUNT: "Ghi nhớ tôi",
        LOGIN: "Đăng Nhập",
        PLEASE_ENTER_PASSWORD: "Vui Lòng Nhập Mật Khẩu",
        PLEASE_ENTER_CODE: "Vui Lòng Nhập Mã Số",
    },

    MainLayout: {
        TEXT_HEADER: "Công Cụ Quản Lý",
    },

    Home: {
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_COLOR: "Màu Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        VEHICLE_CONDITION: "Tình Trạng: ",
        SCHEDULE: "Lịch Trình: ",
        CAR_INFO: "Thông Tin Xe",
    },

    RentedCar: {
        RENTED_CAR_LIST: "Danh Sách Xe Đã Đăng Ký",
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        SCHEDULE: "Lịch Trình: ",
        SUBSCRIBERS: "Người Đăng Ký: ",
        DRIVER: "Tài Xế: ",
        TIME: "Thời Gian: ",
        REVIEW: "Đánh Giá: ",
        COMMENT: "Bình Luận",
        PHONE: "Số Điện Thoại",
    },

    CarRentalManager: {
        CAR_RENTAL_LIST: "Danh Sách Yêu Cầu Đăng Ký Xe",
    },

    CarManager: {
        ADD_CAR: "Thêm Xe",
    },

    DriverManagement: {
        ADD_DRIVER: "Thêm Tài Xế",
        DRIVER_CODE: "Mã Tài Xế",
    },

    Statistical: {
        TOTAL_CAR: "Tổng Số Xe",
        TOTAL_DRIVER: "Tống Số Tài Xế",
        TOTAL_TRIPS: "Tống Số Chuyến Đi",
        FORM_IS_PENDING_CONFIRMATION: "Đơn Chờ Xác Nhận",
        LICENSE_EXPIRES: "Giấy Phép Hết Hạn",
    },

    DriverTripManager: {
        TRIP_LIST: "Danh Sách Chuyến Đi",
    },

    TripManager: {
        TRIP_LIST: "Danh Sách Chuyến Đi",
    },

    RentalCar: {
        RENTAL_CAR: "Đăng Ký Xe",
        CAR_REGISTRATRION_INFOMATION: "Thông Tin Đăng Ký Xe",
        ENTER_START_LOCATION: "-- Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Địa Điểm Kết Thúc --",
        ENTER_START_LOCATION: "-- Nhập Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Nhập Địa Điểm Kết Thúc --",
        ENTER_CAR_RENTAL_REASON: "-- Mục Đích Sử Dụng Xe --",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_NOTE: "-- Ghi Chú --",
        ENTER_PHONE_NUMBER: "-- Số Điện Thoại --",
        START_END_DAY: "Ngày Đi - Ngày Về: ",
        CAR_RENTAL_REASON: "Mục Đích Sử Dụng Xe: ",
        START_LOCATION: "Địa Điểm Xuất Phát: ",
        END_LOCATION: "Địa Điểm Kết Thúc: ",
        NOTE: "Ghi Chú: ",
        PHONE_NUMBER: "Số Điện Thoại: ",
        REGISTRATION_CONFIRMATION: "Xác Nhận Đăng Ký",
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_COLOR: "Màu Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        VEHICLE_CONDITION: "Tình Trạng: ",
        SCHEDULE: "Lịch Trình: ",
    },
    UpdateSchedulePending: {
        UPDATE_SCHEDULE: "Cập Nhật Lịch Trình",
        ENTER_START_LOCATION: "-- Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Địa Điểm Kết Thúc --",
        ENTER_START_LOCATION: "-- Nhập Địa Điểm Xuất Phát --",
        ENTER_END_LOCATION: "-- Nhập Địa Điểm Kết Thúc --",
        ENTER_CAR_RENTAL_REASON: "-- Mục Đích Sử Dụng Xe --",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_NOTE: "-- Ghi Chú --",
        ENTER_PHONE_NUMBER: "-- Số Điện Thoại --",
        START_END_DAY: "Ngày Đi - Ngày Về: ",
        CAR_RENTAL_REASON: "Mục Đích Sử Dụng Xe: ",
        START_LOCATION: "Địa Điểm Xuất Phát: ",
        END_LOCATION: "Địa Điểm Kết Thúc: ",
        NOTE: "Ghi Chú: ",
        PHONE_NUMBER: "Số Điện Thoại: ",
        CAR_LIST: "Danh Sách Xe",
        LICENSE_PLATES: "Biển Số Xe: ",
        CAR_COLOR: "Màu Xe: ",
        CAR_BRAND: "Thương Hiệu: ",
        VEHICLE_CONDITION: "Tình Trạng: ",
        SCHEDULE: "Lịch Trình: ",
    },

    ModalShowAddress: {
        TITLE_START_LOCATION: "Chọn Địa Chỉ Xuất Phát",
        TITLE_END_LOCATION: "Chọn Địa Chỉ Kết Thúc",
        TITLE_LOCATION: "Chọn Địa Chỉ",
    },
    DialogDriverTripManagerFilter: {
        TITLE: "Bộ Lọc Lịch Trình",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_LOCATION: "-- Địa Điểm --",
        STATUS: "Trạng Thái:",
        CAR_TYPE: "Loại Xe:",
        CHOOSE_CAR_TYPE: "-- Chọn Loại Xe --",
        CHOOSE_STATUS: "-- Chọn Trạng Thái --",
        SCHEDULE_CODE: "Mã Lịch Trình:",
        ENTER_SCHEDULE_CODE: "-- Nhập Mã Lịch Trình --",
        TIME: "Thời Gian: ",
        ADDRESS: "Địa Chỉ: ",
    },
    DialogRentedCarFilter: {
        TITLE: "Bộ Lọc Lịch Trình",
        CHOOSE_TIME: "-- Chọn Thời Gian --",
        ENTER_LOCATION: "-- Địa Điểm --",
        STATUS: "Trạng Thái:",
        CAR_TYPE: "Loại Xe:",
        CHOOSE_CAR_TYPE: "-- Chọn Loại Xe --",
        CHOOSE_STATUS: "-- Chọn Trạng Thái --",
        SCHEDULE_CODE: "Mã Lịch Trình:",
        ENTER_SCHEDULE_CODE: "-- Nhập Mã Lịch Trình --",
        TIME: "Thời Gian: ",
        ADDRESS: "Địa Chỉ: ",
    },
};

export default Strings;
